#!/bin/zsh

# few functions with set of commands to be run in specific moments
# during arch linux install
# 
# Usage
#
# BTW_ROOT=/dev/nvme0n1p7 BTW_SWAP=/dev/nvme0n1p6 BTW_EFI=/dev/nvme0n1p1 archlinux
#
# Steps
#
# 1. Get info about installation
# 2. Partition
# 3. Install packages
# 4. Run root commands in chroot
# 5. Run user commands in chroot
# 6. Install aur helper
# 7. Install aur packages
# 8. Make capslock great again

echorun() {
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] run: $@"
  "$@"
}

USERNAME=mrkosmici


basic=(base base-devel linux linux-firmware vim networkmanager zsh git grub efibootmgr github-cli)

packages=(
  acpi
  aisleriot
  alacritty
  bluez bluez-utils
  brightnessctl
  cowsay cmatrix
  cmus
  conky
  dmenu
  dmidecode
  dnsmasq
  exfatprogs
  fd
  feh
  firefox
  fzf
  gnome-keyring
  gnome-themes-extra
  htop
  hwinfo
  i3-wm i3blocks i3lock i3status
  jq
  libhandy
  lsd
  man-db man-pages
  mpv
  neofetch
  ntfs-3g
  openssh
  p7zip
  pacman-contrib
  pcmanfm
  pipewire
  pipewire-pulse
  prettyping
  pv
  pwgen
  rclone
  rsync
  scrot
  speedtest-cli
  sshfs
  sudo
  tldr
  tmux
  translate-shell
  tree
  ttf-meslo-nerd
  unzip
  wget
  xcape
  xclip
  xdotool
  xorg-server xorg-xclock xorg-xev xorg-xinit xorg-xinput xorg-xrandr
  xss-lock
  xterm
  yt-dlp
  zip
  neovim nodejs npm ipython python-poetry pyenv yarn
)


think=(veracrypt
  toilet
  testdisk
  transmission-gtk
  gparted
  scrcpy
  chromium
  ttf-dejavu
  ttf-hack-nerd
  telegram-desktop
  signal-desktop
  android-tools
  lutris
  maim
  libreoffice-fresh
  keepass
  obsidian
  texlive-binextra
  texlive-langpolish
  texlive-latex
  obs-studio)

  games=(atlauncher minecraft-launcher lutris lib32-mesa lib32-vulkan-icd-loader lib32-vulkan-intel vulkan-intel sl)
media=(reaper gimp scribus)
wine=(wine)
aurpackages=(
  alacritty-theme
  alacritty-themes
  debtap
  gtypist
  montserrat-otf
  ngrok
  otf-raleway
  vtop
  yewtube-git
  youtube-search-python-git
)
aurthink=(
  pixiecore-git
  pandoc-bin
  python-backcall
  python-pafy-git
  woeusb
  clockify-cli-bin
  clockify-desktop
  youtube-dl
  octopi
  heroku-cli-bin
)

checkroot() {
  echo "Checking root..."
  (( EUID == 0 )) || die 'need root privileges'
}

btw-presetup () { 
  # This should be started first
  checkroot
  echorun loadkeys pl
  echo "Verifying boot mode..."
  echorun cat /sys/firmware/efi/fw_platform_size
  sleep 3
  echo "Checking internet..."
  echorun ip link
  echorun ping -c 1 archlinux.org
  sleep 3
  echorun timedatectl

  echo "Ok, I will format disks"
  echo root: $BTW_ROOT
  echo swap: $BTW_SWAP
  echo efi: $BTW_EFI

  echo "Formatting disks..."
  sleep 3
  echorun mkfs.ext4 $BTW_ROOT
  echorun mkswap $BTW_SWAP
  echo "Formatted"

  echo "Mounting drives..."
  sleep 3
  echorun mount $BTW_ROOT /mnt
  echorun mount $BTW_EFI --mkdir /mnt/boot
  echorun swapon $BTW_SWAP

  echo "Pacstrapping basic packages"
  sleep 3
  echorun pacstrap -K /mnt ${basic[@]}
  echorun genfstab -U /mnt >> /mnt/etc/fstab
  echorun genfstab -U /mnt

  # turn on color in pacman
  echorun sed -i 's/^#\(Color\)/\1/' /mnt/etc/pacman.conf
}

btw-chroot-root () {
  checkroot
  cat <<EOF > /mnt/var/tmp/run-as-root
  #!/bin/bash
  # set time
  ln -sf /usr/share/zoneinfo/Europe/Warsaw /etc/localtime
  hwclock --systohc
  # generate locales
  locale-gen
  echo set hostname to archforce
  echo archforce >> /etc/hostname
  systemctl enable NetworkManager
  grub-mkconfig -o /boot/grub/grub.cfg
  grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB
  # add user
  useradd --create-home $USERNAME
  usermod -aG wheel $USERNAME
  # add user to sudoers
  sed -i 's/# %wheel ALL/%wheel ALL/' /etc/sudoers
EOF
  
  echorun arch-chroot /mnt bash /var/tmp/run-as-root
}

btw-chroot-user() {
  cat <<EOF > /mnt/var/tmp/run-as-user
  #!/bin/bash
  whoami
  HOME=/home/$USERNAME
  cd \$HOME
  git clone https://aur.archlinux.org/yay-bin.git
  cd \$HOME/yay-bin
  makepkg -si
  cd \$HOME
  rm -rf yay-bin

  # install ohmyzsh
  sh -c "\$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

  # change theme to powerlevel10k
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git \${ZSH_CUSTOM:-\$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
  sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="powerlevel10k\/powerlevel10k"/' ~/.zshrc
  # Install Oh My Zsh plugins
  git clone --depth=1 https://github.com/romkatv/zsh-prompt-benchmark.git \${ZSH_CUSTOM:-\$HOME/.oh-my-zsh/custom}/plugins/zsh-prompt-benchmark
  git clone --depth=1 https://github.com/olets/zsh-abbr.git \${ZSH_CUSTOM:-\$HOME/.oh-my-zsh/custom}/plugins/zsh-abbr
  git clone --depth=1 https://github.com/zsh-users/zsh-autosuggestions.git \${ZSH_CUSTOM:-\$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
  git clone --depth=1 https://github.com/zsh-users/zsh-syntax-highlighting.git \${ZSH_CUSTOM:-\$HOME/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
EOF
  echorun arch-chroot -u $USERNAME /mnt bash /var/tmp/run-as-user
}

makecapslockgreatagain() {
  cat <<EOF > /mnt/usr/share/X11/xkb/symbols/pl_caps
partial alphanumeric_keys

xkb_symbols "hjkl" {
    // make capslock a level5 shift modifier
    include "level5(caps_switch)"

    // Make the following keys capable of using eight levels.
    key.type[Group1] = "EIGHT_LEVEL";

    key <AD07>	{ [ NoSymbol, NoSymbol, NoSymbol, NoSymbol, Prior, Prior ]	};
    key <AD08>	{ [ NoSymbol, NoSymbol, NoSymbol, NoSymbol, Home, Home ]	};
    key <AD09>	{ [ NoSymbol, NoSymbol, NoSymbol, NoSymbol, End, End ]	};
    key <AD10>	{ [ NoSymbol, NoSymbol, NoSymbol, NoSymbol, Next, Next ]	};

    // caps + hjkl
    key <AC06> { [ NoSymbol, NoSymbol, NoSymbol, NoSymbol, Left, Left ] };
    key <AC07> { [ NoSymbol, NoSymbol, NoSymbol, NoSymbol, Down, Down ] };
    key <AC08> { [ NoSymbol, NoSymbol, NoSymbol, NoSymbol, Up, Up ] };
    key <AC09> { [ NoSymbol, NoSymbol, NoSymbol, NoSymbol, Right, Right ] };
};

xkb_symbols "x220" {
    key <LSGT>  { [ Insert, Insert, Insert, Insert ] };
};
EOF
}

btw-install () { echorun pacstrap /mnt ${packages[@]} }
btw-install-aur() { echorun arch-chroot -u $USERNAME /mnt bash yay -S --noconfirm "${aurpackages[@]}" }

btw-setup-gh () {
  TOKEN=$(</var/tmp/token)
  cat <<EOF > /mnt/var/tmp/setup-gh
  HOME=/home/$USERNAME
  mkdir \$HOME/{reps,bin}
  cd \$HOME/reps
  export GH_TOKEN=$TOKEN
  gh repo clone scripts
  gh repo clone dotfiles
  cd \$HOME/reps/dotfiles
  git switch arch-t480s
  chmod +x \$HOME/reps/dotfiles/install
  \$HOME/reps/dotfiles/install
  ln -s \$HOME/reps/scripts/add_daily_note.sh \$HOME/bin/daily
  ln -s \$HOME/reps/scripts/conky-i3bar \$HOME/bin/conky-i3bar
  ln -s \$HOME/reps/scripts/set-theme \$HOME/bin/set-theme
  ln -s \$HOME/reps/scripts/toggler.sh \$HOME/bin/toggler
  ln -s \$HOME/reps/scripts/volumelimiter \$HOME/bin/volumelimiter
EOF
  echorun arch-chroot -u $USERNAME /mnt bash /var/tmp/setup-gh
}

echo running as $(whoami)
echorun fdisk -l 
echo root $BTW_ROOT
echo swap $BTW_SWAP
echo efi $BTW_EFI

usage()  {

  cat <<-EOF
2023-12-03 16:48:40
Usage

you should call:

btw-presetup
btw-chroot-root
btw-chroot-user
makecapslockgreatagain
btw-install
btw-install-aur
arch-chroot -u $USERNAME /mnt bash "gh auth login"
btw-setup-gh
EOF
}

usage

echorun btw-presetup
echorun btw-chroot-root
echorun btw-chroot-user
echorun makecapslockgreatagain
echorun btw-install
echorun btw-install-aur
#arch-chroot -u $USERNAME /mnt bash "gh auth login"
echorun btw-setup-gh 

  # sudo -Hu $USERNAME btw-user-setup
  # sudo -Hu $USERNAME gh auth login
  # sudo -Hu $USERNAME btw-run-after-gh
